/**
 * Recurring task expansion.
 *
 * A recurring task is stored once, as a *template* (`isRecurringTemplate`,
 * `scheduledDate: null`). Occurrences are computed on demand. A real Firestore
 * document is only written when the user actually touches an occurrence
 * (completes, edits, reschedules), and that document carries
 * `parentRecurringTaskId` so the template knows the date is already
 * materialised. This keeps a "every weekday forever" task at one document
 * instead of thousands.
 */

import type { DateKey, RecurrenceRule, Task } from '@/types/models';
import { addDays, dayOfWeek, daysInMonth, diffDays, fromDateKey } from '@/utils/date';

export function occursOn(rule: RecurrenceRule, date: DateKey): boolean {
  if (rule.type === 'none') return false;
  if (date < rule.startDate) return false;
  if (rule.endDate && date > rule.endDate) return false;

  const dow = dayOfWeek(date);

  switch (rule.type) {
    case 'daily':
      return true;
    case 'weekdays':
      return dow >= 1 && dow <= 5;
    case 'weekends':
      return dow === 0 || dow === 6;
    case 'weekly': {
      const target = rule.daysOfWeek?.[0] ?? dayOfWeek(rule.startDate);
      return dow === target;
    }
    case 'specific_days':
      return (rule.daysOfWeek ?? []).includes(dow);
    case 'monthly': {
      const anchorDay = rule.dayOfMonth ?? fromDateKey(rule.startDate).getDate();
      const d = fromDateKey(date);
      const lastDay = daysInMonth(d.getFullYear(), d.getMonth());
      // Clamp so "31st monthly" still fires on 30 April / 28 February.
      return d.getDate() === Math.min(anchorDay, lastDay);
    }
    case 'interval': {
      const step = Math.max(1, Math.round(rule.interval ?? 1));
      return diffDays(rule.startDate, date) % step === 0;
    }
    default:
      return false;
  }
}

/** Occurrence dates inside an inclusive window. */
export function occurrencesInRange(
  rule: RecurrenceRule,
  from: DateKey,
  to: DateKey,
  limit = 400,
): DateKey[] {
  const out: DateKey[] = [];
  let cursor = from < rule.startDate ? rule.startDate : from;
  let guard = 0;
  while (cursor <= to && out.length < limit && guard < 2000) {
    guard += 1;
    if (occursOn(rule, cursor)) out.push(cursor);
    cursor = addDays(cursor, 1);
  }
  return out;
}

export function nextOccurrence(rule: RecurrenceRule, after: DateKey): DateKey | null {
  let cursor = addDays(after, 1);
  if (cursor < rule.startDate) cursor = rule.startDate;
  for (let i = 0; i < 400; i += 1) {
    if (rule.endDate && cursor > rule.endDate) return null;
    if (occursOn(rule, cursor)) return cursor;
    cursor = addDays(cursor, 1);
  }
  return null;
}

/** Stable id for a virtual (not yet written) occurrence. */
export function virtualOccurrenceId(templateId: string, date: DateKey): string {
  return `virtual:${templateId}:${date}`;
}

export function isVirtualOccurrence(taskId: string): boolean {
  return taskId.startsWith('virtual:');
}

export function parseVirtualOccurrence(
  taskId: string,
): { templateId: string; date: DateKey } | null {
  if (!isVirtualOccurrence(taskId)) return null;
  const parts = taskId.split(':');
  if (parts.length !== 3) return null;
  return { templateId: parts[1], date: parts[2] };
}

/** Builds the in-memory task an occurrence renders as, before materialisation. */
export function buildVirtualOccurrence(template: Task, date: DateKey): Task {
  return {
    ...template,
    id: virtualOccurrenceId(template.id, date),
    scheduledDate: date,
    status: 'not_started',
    completedAt: null,
    actualMinutes: null,
    isTopPriority: false,
    topPriorityOrder: null,
    isRecurringTemplate: false,
    parentRecurringTaskId: template.id,
    // A template's subtask completion must not leak into future occurrences.
    subtasks: template.subtasks.map((s) => ({ ...s, done: false })),
    notificationId: null,
  };
}

/**
 * Merges stored tasks for a date with the virtual occurrences generated by
 * recurring templates, skipping any date that already has a real document.
 */
export function expandTasksForDate(
  storedTasks: Task[],
  templates: Task[],
  date: DateKey,
): Task[] {
  const materialised = new Set(
    storedTasks
      .filter((t) => t.parentRecurringTaskId && t.scheduledDate === date)
      .map((t) => t.parentRecurringTaskId as string),
  );

  const virtuals: Task[] = [];
  for (const template of templates) {
    if (!template.recurrenceRule) continue;
    if (materialised.has(template.id)) continue;
    if (!occursOn(template.recurrenceRule, date)) continue;
    virtuals.push(buildVirtualOccurrence(template, date));
  }

  return [...storedTasks.filter((t) => !t.isRecurringTemplate), ...virtuals];
}

export const RECURRENCE_LABELS: Record<RecurrenceRule['type'], string> = {
  none: 'Does not repeat',
  daily: 'Every day',
  weekdays: 'Weekdays',
  weekends: 'Weekends',
  weekly: 'Weekly',
  specific_days: 'Specific days',
  monthly: 'Monthly',
  interval: 'Custom interval',
};

export function describeRecurrence(rule: RecurrenceRule | null | undefined): string {
  if (!rule || rule.type === 'none') return 'Does not repeat';
  const dayNames = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  switch (rule.type) {
    case 'specific_days': {
      const days = (rule.daysOfWeek ?? []).slice().sort((a, b) => a - b);
      if (days.length === 0) return 'Specific days';
      return days.map((d) => dayNames[d]).join(' · ');
    }
    case 'weekly':
      return `Every ${dayNames[rule.daysOfWeek?.[0] ?? dayOfWeek(rule.startDate)]}`;
    case 'monthly':
      return `Monthly on day ${rule.dayOfMonth ?? fromDateKey(rule.startDate).getDate()}`;
    case 'interval':
      return `Every ${Math.max(1, rule.interval ?? 1)} days`;
    default:
      return RECURRENCE_LABELS[rule.type];
  }
}
