/**
 * Task occurrence expansion.
 *
 * Pure and Firebase-free so it can be unit tested directly; `taskService`
 * re-exports these and adds the persistence around them.
 */

import type { DateKey, Task } from '@/types/models';
import { isScheduledOn, virtualOccurrenceId } from './index';

/** The in-memory task an occurrence renders as before it is materialised. */
export function buildVirtualOccurrence(template: Task, dateKey: DateKey): Task {
  return {
    ...template,
    id: virtualOccurrenceId(template.id, dateKey),
    dateKey,
    status: 'pending',
    completedAt: null,
    isRecurringTemplate: false,
    parentTaskId: template.id,
    recurrence: null,
    notificationId: null,
    carryCount: 0,
  };
}

/**
 * Merges the tasks stored for a date with the occurrences generated by
 * recurring templates, skipping any template that already has a real document
 * on that date.
 */
export function expandTasksForDate(
  storedTasks: Task[],
  templates: Task[],
  dateKey: DateKey,
): Task[] {
  const materialised = new Set(
    storedTasks
      .filter((t) => t.parentTaskId && t.dateKey === dateKey)
      .map((t) => t.parentTaskId as string),
  );

  const virtuals: Task[] = [];
  for (const template of templates) {
    if (!template.recurrence) continue;
    if (materialised.has(template.id)) continue;
    if (!isScheduledOn(template.recurrence, dateKey)) continue;
    virtuals.push(buildVirtualOccurrence(template, dateKey));
  }

  return [...storedTasks.filter((t) => !t.isRecurringTemplate), ...virtuals];
}
